// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ServicesColumns holds the columns for the "services" table.
	ServicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "endpoint", Type: field.TypeString, Size: 500},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"SERVICE_TYPE_UNSPECIFIED", "SERVICE_TYPE_HTTP", "SERVICE_TYPE_GRPC", "SERVICE_TYPE_DATABASE", "SERVICE_TYPE_CACHE", "SERVICE_TYPE_QUEUE", "SERVICE_TYPE_STORAGE", "SERVICE_TYPE_EXTERNAL_API", "SERVICE_TYPE_MICROSERVICE", "SERVICE_TYPE_OTHER"}, Default: "SERVICE_TYPE_UNSPECIFIED"},
		{Name: "status", Type: field.TypeString, Size: 50, Default: "active"},
		{Name: "last_heartbeat", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updated_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
	}
	// ServicesTable holds the schema information for the "services" table.
	ServicesTable = &schema.Table{
		Name:       "services",
		Columns:    ServicesColumns,
		PrimaryKey: []*schema.Column{ServicesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "service_name_endpoint",
				Unique:  true,
				Columns: []*schema.Column{ServicesColumns[1], ServicesColumns[2]},
			},
			{
				Name:    "service_type",
				Unique:  false,
				Columns: []*schema.Column{ServicesColumns[3]},
			},
			{
				Name:    "service_status",
				Unique:  false,
				Columns: []*schema.Column{ServicesColumns[4]},
			},
			{
				Name:    "service_last_heartbeat",
				Unique:  false,
				Columns: []*schema.Column{ServicesColumns[5]},
			},
			{
				Name:    "service_type_status",
				Unique:  false,
				Columns: []*schema.Column{ServicesColumns[3], ServicesColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ServicesTable,
	}
)

func init() {
	ServicesTable.Annotation = &entsql.Annotation{
		Table:     "services",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_unicode_ci",
		Options:   "ENGINE=InnoDB",
	}
}
