//go:build ignore

package main

import (
	"log"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

func main() {
	cfg := &gen.Config{
		Header: `
// Code generated by ent, DO NOT EDIT.
`,
		Package: "watchdog/ent",
		Target:  "./ent",
	}

	err := entc.Generate("./ent/schema", cfg)
	if err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
	
	log.Println("Ent code generation completed successfully")
}