// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/watchdog.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_UNSPECIFIED  ServiceType = 0
	ServiceType_SERVICE_TYPE_HTTP         ServiceType = 1
	ServiceType_SERVICE_TYPE_GRPC         ServiceType = 2
	ServiceType_SERVICE_TYPE_DATABASE     ServiceType = 3
	ServiceType_SERVICE_TYPE_CACHE        ServiceType = 4
	ServiceType_SERVICE_TYPE_QUEUE        ServiceType = 5
	ServiceType_SERVICE_TYPE_STORAGE      ServiceType = 6
	ServiceType_SERVICE_TYPE_EXTERNAL_API ServiceType = 7
	ServiceType_SERVICE_TYPE_MICROSERVICE ServiceType = 8
	ServiceType_SERVICE_TYPE_OTHER        ServiceType = 9
	ServiceType_SERVICE_TYPE_SYSTEMD      ServiceType = 10
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0:  "SERVICE_TYPE_UNSPECIFIED",
		1:  "SERVICE_TYPE_HTTP",
		2:  "SERVICE_TYPE_GRPC",
		3:  "SERVICE_TYPE_DATABASE",
		4:  "SERVICE_TYPE_CACHE",
		5:  "SERVICE_TYPE_QUEUE",
		6:  "SERVICE_TYPE_STORAGE",
		7:  "SERVICE_TYPE_EXTERNAL_API",
		8:  "SERVICE_TYPE_MICROSERVICE",
		9:  "SERVICE_TYPE_OTHER",
		10: "SERVICE_TYPE_SYSTEMD",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED":  0,
		"SERVICE_TYPE_HTTP":         1,
		"SERVICE_TYPE_GRPC":         2,
		"SERVICE_TYPE_DATABASE":     3,
		"SERVICE_TYPE_CACHE":        4,
		"SERVICE_TYPE_QUEUE":        5,
		"SERVICE_TYPE_STORAGE":      6,
		"SERVICE_TYPE_EXTERNAL_API": 7,
		"SERVICE_TYPE_MICROSERVICE": 8,
		"SERVICE_TYPE_OTHER":        9,
		"SERVICE_TYPE_SYSTEMD":      10,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_watchdog_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_proto_watchdog_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{0}
}

type CheckServiceHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckServiceHealthRequest) Reset() {
	*x = CheckServiceHealthRequest{}
	mi := &file_proto_watchdog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckServiceHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServiceHealthRequest) ProtoMessage() {}

func (x *CheckServiceHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchdog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServiceHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckServiceHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{0}
}

func (x *CheckServiceHealthRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_watchdog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchdog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{1}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_watchdog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchdog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,5,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Type          ServiceType            `protobuf:"varint,6,opt,name=type,proto3,enum=watchdog.ServiceType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_proto_watchdog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchdog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ServiceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *ServiceInfo) GetType() ServiceType {
	if x != nil {
		return x.Type
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

type RegisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Type          ServiceType            `protobuf:"varint,3,opt,name=type,proto3,enum=watchdog.ServiceType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_proto_watchdog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchdog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterServiceRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterServiceRequest) GetType() ServiceType {
	if x != nil {
		return x.Type
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_proto_watchdog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchdog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterServiceResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegisterServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnregisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterServiceRequest) Reset() {
	*x = UnregisterServiceRequest{}
	mi := &file_proto_watchdog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterServiceRequest) ProtoMessage() {}

func (x *UnregisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchdog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterServiceRequest.ProtoReflect.Descriptor instead.
func (*UnregisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{6}
}

func (x *UnregisterServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type UnregisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterServiceResponse) Reset() {
	*x = UnregisterServiceResponse{}
	mi := &file_proto_watchdog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterServiceResponse) ProtoMessage() {}

func (x *UnregisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchdog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterServiceResponse.ProtoReflect.Descriptor instead.
func (*UnregisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_proto_watchdog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchdog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{8}
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_proto_watchdog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchdog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{9}
}

func (x *ListServicesResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

type UpdateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          ServiceType            `protobuf:"varint,4,opt,name=type,proto3,enum=watchdog.ServiceType" json:"type,omitempty"`
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_proto_watchdog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchdog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *UpdateServiceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServiceRequest) GetType() ServiceType {
	if x != nil {
		return x.Type
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *UpdateServiceRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type UpdateServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceResponse) Reset() {
	*x = UpdateServiceResponse{}
	mi := &file_proto_watchdog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceResponse) ProtoMessage() {}

func (x *UpdateServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchdog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceResponse.ProtoReflect.Descriptor instead.
func (*UpdateServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_watchdog_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_watchdog_proto protoreflect.FileDescriptor

const file_proto_watchdog_proto_rawDesc = "" +
	"\n" +
	"\x14proto/watchdog.proto\x12\bwatchdog\":\n" +
	"\x19CheckServiceHealthRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb7\x01\n" +
	"\vServiceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12%\n" +
	"\x0elast_heartbeat\x18\x05 \x01(\x03R\rlastHeartbeat\x12)\n" +
	"\x04type\x18\x06 \x01(\x0e2\x15.watchdog.ServiceTypeR\x04type\"s\n" +
	"\x16RegisterServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.watchdog.ServiceTypeR\x04type\"R\n" +
	"\x17RegisterServiceResponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x18UnregisterServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"5\n" +
	"\x19UnregisterServiceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x15\n" +
	"\x13ListServicesRequest\"I\n" +
	"\x14ListServicesResponse\x121\n" +
	"\bservices\x18\x01 \x03(\v2\x15.watchdog.ServiceInfoR\bservices\"\xa8\x01\n" +
	"\x14UpdateServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.watchdog.ServiceTypeR\x04type\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\"1\n" +
	"\x15UpdateServiceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\xae\x02\n" +
	"\vServiceType\x12\x1c\n" +
	"\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SERVICE_TYPE_HTTP\x10\x01\x12\x15\n" +
	"\x11SERVICE_TYPE_GRPC\x10\x02\x12\x19\n" +
	"\x15SERVICE_TYPE_DATABASE\x10\x03\x12\x16\n" +
	"\x12SERVICE_TYPE_CACHE\x10\x04\x12\x16\n" +
	"\x12SERVICE_TYPE_QUEUE\x10\x05\x12\x18\n" +
	"\x14SERVICE_TYPE_STORAGE\x10\x06\x12\x1d\n" +
	"\x19SERVICE_TYPE_EXTERNAL_API\x10\a\x12\x1d\n" +
	"\x19SERVICE_TYPE_MICROSERVICE\x10\b\x12\x16\n" +
	"\x12SERVICE_TYPE_OTHER\x10\t\x12\x18\n" +
	"\x14SERVICE_TYPE_SYSTEMD\x10\n" +
	"2\xfd\x03\n" +
	"\x0fWatchdogService\x12>\n" +
	"\tGetHealth\x12\x17.watchdog.HealthRequest\x1a\x18.watchdog.HealthResponse\x12V\n" +
	"\x0fRegisterService\x12 .watchdog.RegisterServiceRequest\x1a!.watchdog.RegisterServiceResponse\x12\\\n" +
	"\x11UnregisterService\x12\".watchdog.UnregisterServiceRequest\x1a#.watchdog.UnregisterServiceResponse\x12M\n" +
	"\fListServices\x12\x1d.watchdog.ListServicesRequest\x1a\x1e.watchdog.ListServicesResponse\x12P\n" +
	"\rUpdateService\x12\x1e.watchdog.UpdateServiceRequest\x1a\x1f.watchdog.UpdateServiceResponse\x12S\n" +
	"\x12CheckServiceHealth\x12#.watchdog.CheckServiceHealthRequest\x1a\x18.watchdog.HealthResponseB\x0eZ\fwatchdog/apib\x06proto3"

var (
	file_proto_watchdog_proto_rawDescOnce sync.Once
	file_proto_watchdog_proto_rawDescData []byte
)

func file_proto_watchdog_proto_rawDescGZIP() []byte {
	file_proto_watchdog_proto_rawDescOnce.Do(func() {
		file_proto_watchdog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_watchdog_proto_rawDesc), len(file_proto_watchdog_proto_rawDesc)))
	})
	return file_proto_watchdog_proto_rawDescData
}

var file_proto_watchdog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_watchdog_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_watchdog_proto_goTypes = []any{
	(ServiceType)(0),                  // 0: watchdog.ServiceType
	(*CheckServiceHealthRequest)(nil), // 1: watchdog.CheckServiceHealthRequest
	(*HealthRequest)(nil),             // 2: watchdog.HealthRequest
	(*HealthResponse)(nil),            // 3: watchdog.HealthResponse
	(*ServiceInfo)(nil),               // 4: watchdog.ServiceInfo
	(*RegisterServiceRequest)(nil),    // 5: watchdog.RegisterServiceRequest
	(*RegisterServiceResponse)(nil),   // 6: watchdog.RegisterServiceResponse
	(*UnregisterServiceRequest)(nil),  // 7: watchdog.UnregisterServiceRequest
	(*UnregisterServiceResponse)(nil), // 8: watchdog.UnregisterServiceResponse
	(*ListServicesRequest)(nil),       // 9: watchdog.ListServicesRequest
	(*ListServicesResponse)(nil),      // 10: watchdog.ListServicesResponse
	(*UpdateServiceRequest)(nil),      // 11: watchdog.UpdateServiceRequest
	(*UpdateServiceResponse)(nil),     // 12: watchdog.UpdateServiceResponse
}
var file_proto_watchdog_proto_depIdxs = []int32{
	0,  // 0: watchdog.ServiceInfo.type:type_name -> watchdog.ServiceType
	0,  // 1: watchdog.RegisterServiceRequest.type:type_name -> watchdog.ServiceType
	4,  // 2: watchdog.ListServicesResponse.services:type_name -> watchdog.ServiceInfo
	0,  // 3: watchdog.UpdateServiceRequest.type:type_name -> watchdog.ServiceType
	2,  // 4: watchdog.WatchdogService.GetHealth:input_type -> watchdog.HealthRequest
	5,  // 5: watchdog.WatchdogService.RegisterService:input_type -> watchdog.RegisterServiceRequest
	7,  // 6: watchdog.WatchdogService.UnregisterService:input_type -> watchdog.UnregisterServiceRequest
	9,  // 7: watchdog.WatchdogService.ListServices:input_type -> watchdog.ListServicesRequest
	11, // 8: watchdog.WatchdogService.UpdateService:input_type -> watchdog.UpdateServiceRequest
	1,  // 9: watchdog.WatchdogService.CheckServiceHealth:input_type -> watchdog.CheckServiceHealthRequest
	3,  // 10: watchdog.WatchdogService.GetHealth:output_type -> watchdog.HealthResponse
	6,  // 11: watchdog.WatchdogService.RegisterService:output_type -> watchdog.RegisterServiceResponse
	8,  // 12: watchdog.WatchdogService.UnregisterService:output_type -> watchdog.UnregisterServiceResponse
	10, // 13: watchdog.WatchdogService.ListServices:output_type -> watchdog.ListServicesResponse
	12, // 14: watchdog.WatchdogService.UpdateService:output_type -> watchdog.UpdateServiceResponse
	3,  // 15: watchdog.WatchdogService.CheckServiceHealth:output_type -> watchdog.HealthResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_watchdog_proto_init() }
func file_proto_watchdog_proto_init() {
	if File_proto_watchdog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_watchdog_proto_rawDesc), len(file_proto_watchdog_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_watchdog_proto_goTypes,
		DependencyIndexes: file_proto_watchdog_proto_depIdxs,
		EnumInfos:         file_proto_watchdog_proto_enumTypes,
		MessageInfos:      file_proto_watchdog_proto_msgTypes,
	}.Build()
	File_proto_watchdog_proto = out.File
	file_proto_watchdog_proto_goTypes = nil
	file_proto_watchdog_proto_depIdxs = nil
}
